myshop/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),         
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.product_main, name='product_main'),
	url(r'^new/$', views.product_new, name='product_new'),
    url(r'^catalog/$', views.product_list, name='product_list'),
    url(r'^Brends/$', views.product_brends, name='product_brends'),
    url(r'^About_shop/$', views.product_shop, name='product_shop'),
    url(r'^About_sweets/$', views.product_sweets, name='product_sweets'),
    url(r'^(?P<category_slug>[-\w]+)/$',views.product_list,name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),

]

myshop/shop/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                           args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                           args=[self.id, self.slug])

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    product = Product.objects.filter(available=True)
    paginator = Paginator(product, 12)
    page = request.GET.get('page') 
    try:  
        products = paginator.page(page)  
    except PageNotAnInteger:  
        # Если страница не является целым числом, поставим первую страницу  
        products = paginator.page(1)  
    except EmptyPage:  
        # Если страница больше максимальной, доставить последнюю страницу результатов  
        products = paginator.page(paginator.num_pages)    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        product = product.filter(category=category)
        paginator = Paginator(product, 12)
        page = request.GET.get('page') 
        try:  
          products = paginator.page(page)  
        except PageNotAnInteger:  
            # Если страница не является целым числом, поставим первую страницу  
          products = paginator.page(1)  
        except EmptyPage:  
            # Если страница больше максимальной, доставить последнюю страницу результатов  
          products = paginator.page(paginator.num_pages)

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'page': page,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})


def product_main(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    product = Product.objects.filter(available=True).order_by('-created')
    paginator = Paginator(product, 4)
    page = request.GET.get('page') 
    try:  
        products = paginator.page(page)  
    except PageNotAnInteger:  
        # Если страница не является целым числом, поставим первую страницу  
        products = paginator.page(1)  
    except EmptyPage:  
        # Если страница больше максимальной, доставить последнюю страницу результатов  
        products = paginator.page(paginator.num_pages)    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/main.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

def product_new(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    product = Product.objects.filter(available=True).order_by('-created')
    paginator = Paginator(product, 10)
    page = request.GET.get('page') 
    try:  
        products = paginator.page(page)  
    except PageNotAnInteger:  
        # Если страница не является целым числом, поставим первую страницу  
        products = paginator.page(1)  
    except EmptyPage:  
        # Если страница больше максимальной, доставить последнюю страницу результатов  
        products = paginator.page(paginator.num_pages)    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/new.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_brends(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    product = Product.objects.filter(available=True)
    paginator = Paginator(product, 15)
    page = request.GET.get('page') 
    try:  
        products = paginator.page(page)  
    except PageNotAnInteger:  
        # Если страница не является целым числом, поставим первую страницу  
        products = paginator.page(1)  
    except EmptyPage:  
        # Если страница больше максимальной, доставить последнюю страницу результатов  
        products = paginator.page(paginator.num_pages)    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/brends.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_sweets(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    product = Product.objects.filter(available=True)
    paginator = Paginator(product, 15)
    page = request.GET.get('page') 
    try:  
        products = paginator.page(page)  
    except PageNotAnInteger:  
        # Если страница не является целым числом, поставим первую страницу  
        products = paginator.page(1)  
    except EmptyPage:  
        # Если страница больше максимальной, доставить последнюю страницу результатов  
        products = paginator.page(paginator.num_pages)    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/history_sweets.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_shop(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    product = Product.objects.filter(available=True)
    paginator = Paginator(product, 15)
    page = request.GET.get('page') 
    try:  
        products = paginator.page(page)  
    except PageNotAnInteger:  
        # Если страница не является целым числом, поставим первую страницу  
        products = paginator.page(1)  
    except EmptyPage:  
        # Если страница больше максимальной, доставить последнюю страницу результатов  
        products = paginator.page(paginator.num_pages)    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/shop_ios.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

myshop/shop/templates/shop/product/brends.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Brends{% endif %}
{% endblock %}
{% block content %}
<div class="new_body">
    <div id="main_n" class="product-list">
       <a href=""><img src="{% static 'css/png/Oreo_95.png '%}"  style="    flex-shrink: 0; object-fit: contain; width: 330px; height: 300px"></a>
       <a href=""><img src="{% static 'css/png/logo-milka.png '%}"  style="    flex-shrink: 0; object-fit: contain; width: 330px; height: 300px"></a>
       <a href=""><img src="{% static 'css/png/KitKat_logo.svg_.png' %}"  style="    flex-shrink: 0; object-fit: contain; width: 330px; height: 300px"></a>
        <a href=""><img src="{% static 'css/png/Snickers_logo.png' %}"  style="    flex-shrink: 0; object-fit: contain; width: 330px; height: 300px"></a>
       <a href=""><img src="{% static 'css/png/milkiway.jpg' %}"  style="    flex-shrink: 0; object-fit: contain; width: 330px; height: 300px"></a>
       <a href=""><img src="{% static 'css/png/twix.png' %}"  style="    flex-shrink: 0; object-fit: contain; width: 330px; height: 300px"></a>  
       
    </div>
</div>
{% endblock %}

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" style="    flex-shrink: 0; object-fit: contain; width: 50%; height: 450px">
        <h1 style="margin: 10px">{{ product.name }}</h1>
        <h2 style="margin: 10px"><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price" style="margin: 10px">${{ product.price }}</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
		    {{ cart_product_form }}
		    {% csrf_token %}
		    <input type="submit" value="Add to cart" style="margin: 10px">
		</form>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

myshop/shop/templates/shop/product/history_sweets.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Brends{% endif %}
{% endblock %}
{% block content %}
<div class="new_body">
    <div id="main_n" class="product-list">
    	<h1 class="entry-title">ЯПОНСКИЕ СЛАДОСТИ</h1>
		<span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;margin-top: 10px">Для японской кухни традиционно важен внешний облик блюд. Ингредиенты всегда нарезают на кусочки привлекательной формы, их изощренно сервируют на блюдах и тщательно подбирают посуду. Все делается для того, чтобы за обеденным столом было приятно и красиво. Эта же философия распространяется и на сладости. Кондитерские изделия, подобные настоящим произведениям искусства и сладости, исполненные в виде растительных или животных мотивов — это то, чем славится японская кондитерская традиция.</span>
		<p style="text-align: justify;">Традиционными японскими сладостями являются <strong><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;">вагаси</span></strong>. Они выделяются в отдельную группу, так как при их приготовлении используются только растительные ингредиенты и никогда не применяются животные жиры, молочные продукты или желатин. От европейских — приготовленных на основе сахара — они отличаются менее сладким вкусом и более нежным ароматом.<br>
		Кондитерская «<em>Торая</em>» занимается кондитерским делом на протяжении почти половины тысячелетия. В настоящее время она работает над популяризацией японских сладостей (вагаси) за рубежом. В этом году исполняется тридцать лет с момента открытия магазина «Торая» в Париже. Ее кондитеры воссоздали набор сладостей в старинном стиле. Такие лакомства поставляли к императорскому двору. Современным мастерам удалось идентично передать форму и вкус сладостей, а также подобрать утонченные цветовые сочетания.</p>
		<p style="text-align: justify;">Многие из сладостей имеют поэтичные имена. К примеру, “Тодзакура” означает — “цветы сакуры вдалеке”. Внешний вид и название вызывает ассоциации с цветущими деревьями сакуры&nbsp;на склонах гор.</p>
		<p style="text-align: justify;">В 14-15 веке японское кондитерское искусство претерпело существенные изменения. Япония вступила в торговые отношения с Португалией и Испанией, которые стали для неё источником новых рецептов и ингредиентов. Традиционные японские сладости стали приобретать новые вкусовые оттенки. В частности, при их изготовлении стал использоваться сахар, что существенно облегчило задачу кондитеров: ранее сладость достигалась за счёт других компонентов, например, красной фасоли-адзуки или сушёных фруктов.</p>
		<p style="text-align: justify;">Классический пример этой технологии — японские сладости <strong><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;">данго</span></strong>. Приготовленные на пару, рисовые шарики при подаче смазывались сладкой бобовой пастой либо поливались сиропом со вкусом соевого соуса. Подслащенные таким образом, они продавались в средние века с торговых лотков вдоль почтовых дорог, а также в чайных домиках на территории храмов. Обычно насаживались на бамбуковую палочку по две штуки. Их было удобно брать с собой в дорогу и есть прямо на ходу. В отличие от императорских сладостей, данго имели непритязательный вид, но это народное лакомство до сих пор сохраняется в меню стрит-фуда.</p>
		<p style="text-align: justify;">В период правления императора Муцухито (1868—1912) огромное влияние на вагаси оказали появившиеся в Японии западные сладости. (Не случайно имя Мэйдзи, которое взял себе император, означает «просвещённое правление»). И действительно, этот период ознаменовался отказом Японии от самоизоляции. В конце XIX века, в закрытую до того от остального мира страну, хлынули элементы европейской культуры. Собственно, термин «вагаси» появился в лексиконе островного обывателя только после 1912 года, чтобы отличать исконно японские сладости от появившихся заморских «эмигрантов».<br>
		Современные вагаси часто сочетают в себе и традиционные и западные элементы, хотя в целом видение кондитерского искусства, безусловно, остается типично японским.</p>
		<p style="text-align: justify;">Возможно, эти сладости сохранили к себе почтительное отношение японцев с тех пор, когда в период между XV и XVI веками, конфеты были завезены в Японию торговцами из Европы. (Слово компэйто происходит от португальского — «<em>confeit</em>o», что означает леденец, <strong><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;">сахарная конфета</span></strong>).<br>
		В то время в Японии ещё не была освоена технология рафинирования сахара, а поскольку в производстве компэйто сахар используется в больших количествах, — они были очень редким и дорогим продуктом. Так, в 1569 году за коробку этих конфет тогдашний японский властитель Ода Нобунага разрешил португальскому миссионеру основать в Японии христианское представительство… &nbsp;Кстати, изготовление компэйто и сейчас обычно занимает от 7 до 10 дней, ведь конфеты до сих пор изготавливаются практически вручную.</p>
		<p style="text-align: justify;">С появлением сахара в рецептах кондитеров страны Восходящего Солнца, развитии получило и традиционное японское искусство изготовления леденцов в форме животных, известное с XVIII века под названием <strong><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;">амэдзаику (</span></strong><span style="font-family: arial, helvetica, sans-serif; font-size: 14pt;">аmezaiku</span>).<br>
		Это искусство пришло в Японию из Китая. Вначале оно имело место исключительно в храмах Киото. Позже, (с развитием уличных искусств и торговли), визуальная привлекательность сделала леденцы популярным стрит-артом и формой развлечения для простых людей.<br>
		Изначально, при изготовлении леденцов-Amezaiku японские ремесленники использовали в оформлении только красный и белый цвета.<br>
		С виду фигурка животного выглядела простенько, чуть сложнее наших неказистых сахарных <петушков и белочек на палочке, изготавливаемых в домашних условиях при помощи форм для отливки. Но, в отличие от них, леденцы-амэзаику являются хэндмейдом от и до. При этом, изготовление включает в себя множество этапов и требует большой сноровки.<br>
		Первоначально, подобно стеклодуву, ремесленник выдувал «карамельный шарик» на конце стебля тростника, чтобы из такой заготовки вылепить-выщипать требуемую фигурку.</p>
		<p style="text-align: justify;">Для этого крахмальную патоку кипятили до тех пор, пока она не становилась, как тесто и не принимала полупрозрачной вид. </a>Потом материал нагревался на древесном угле, что делало его очень пластичным. Затем основа делилась на небольшие порции, из которых и мастерили фигурки.<br>
		Формы животных нужно формировать «с пылу-жару», ловко используя крошечные ножницы и палочки. Иногда мастеру приходится разминать, вытягивать и сгибать горячий материал пальцами, отчего процедура бывает болезненной. Для квалифицированного ремесленника amezaiku на одну незатейливую фигурку уходило около двух-трех минут.</p>
		<p style="text-align: justify;"><a id="леденец"></a>Пик популярности леденцов в Японии пришелся на период после Второй мировой войны. Но уже в 70-х они стали исчезать с улиц из-за более привлекательных технологических достижений и засилия фасованных кондитерских новинок. В настоящее время в Японии еще существуют магазины, продающие леденцы, изготовленные по ручной технологии аmezaiku, однако мастеров продолжающих традицию амэдзаику, осталось немного. Одним из ее апологетов является японец <strong><span style="font-family: arial, helvetica, sans-serif; font-size: 10pt;">Takafumi Ichiyanagi</span></strong>.</p>
		<p style="text-align: justify;">Баланс между новыми направлениями в кондитерском бизнесе и запросами покупателей, привыкших к традиционному вкусу продуктов можно сравнить с восприятием изменения городского ландшафта. «Кое-кто, может быть, хотел бы, чтобы Токио сохранился неизменным с периода Эдо, но если попробовать действительно пожить в таком традиционном городе, вы скоро ощутите, насколько он неудобен для жизни. Некоторые изменения необходимы», — замечает глава знаменитой кондитерской компании «Торая».</p>
    </div>
</div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url 'shop:product_list' %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1 class="category">{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="    flex-shrink: 0; object-fit: contain; width: 100%; height: 200px">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
        {% endfor %}
         {% include "shop/product/pagination.html" with page=products %} 
    </div>
{% endblock %}

myshop/shop/templates/shop/product/main.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
	<div class="slider_p">
			<div id="slider-wrap">
			    <div id="active-slide">
			        <div id="slider">
						<div class="slide"><a href="{% url 'shop:product_list' %}"><img src="{% static 'css/png/slaider_pupblick_1.jpg' %}" width="100%" height="100%"></a></div>
			            <div class="slide"><img src="{% static 'css/png/slaider_pupblick_2.jpg' %}" width="100%" height="100%"></div>
			            <div class="slide"><img src="{% static 'css/png/slaider_pupblick_3.jpg' %}" width="100%" height="100%"></div>
			        </div>
			    </div>
			</div>
		</div>
			<div class="rubrick">
				<a class="rubrick_a" href="{% url 'shop:product_list' %}">
	Popular categories in the store</a>
			</div>
			<div class="rubrick_main">
				<a href="chocolate" class="rubrick_img"><img src="{% static 'css/png/rubrik-1.jpg' %}" width="100%" height="100%"></a>
				<a href="candies" class="rubrick_img"><img src="{% static 'css/png/rubrik-2.jpg' %}" width="100%" height="100%"></a>
				<a href="marmalade" class="rubrick_img"><img src="{% static 'css/png/rubrik-3.jpg' %}" width="100%" height="100%"></a>
			</div>
			<div class="Popular_p">
				<a class="rubrick_a" href="{% url 'shop:product_new' %}">

	New products in the store</a>
			</div>
			<div class="Popular_main">
				<div id="slider-wrap_p">
				    <div id="active-slide_p">
				        <div id="slider_p">
				            <div class="slide_p">
								{% for product in products %}
								            <div class="item">
								                <a href="{{ product.get_absolute_url }}">
								                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="    flex-shrink: 0; object-fit: contain; width: 100%; height: 200px">
								                </a>
								                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
								                ${{ product.price }}
								            </div>
								        {% endfor %}
				            </div>
				        </div>
				    </div>
				</div>
			</div>
{% endblock %}

myshop/shop/templates/shop/product/new.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}New products{% endif %}
{% endblock %}
{% block content %}
<div class="new_body">
    <div id="main_n" class="product-list">
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="    flex-shrink: 0; object-fit: contain; width: 100%; height: 200px">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
        {% endfor %}
         {% include "shop/product/pagination.html" with page=products %} 
    </div>
</div>
{% endblock %}

myshop/shop/templates/shop/product/pagination.html
<div class="pagination">  
 <span class="step-links">  
  {% if page.has_previous %}  
      <a href="?page={{ page.previous_page_number }}">Previous</a>  
  {% endif %}  
    <span class="current">  
  Page {{ page.number }} of {{ page.paginator.num_pages }}.  
    </span>  
  {% if page.has_next %}  
        <a href="?page={{ page.next_page_number }}">Next</a>  
  {% endif %}  
  </span>  
</div>

myshop/shop/templates/shop/product/shop_ios.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Brends{% endif %}
{% endblock %}
{% block content %}
<div class="new_body">
    <div id="main_n" class="product-list">
       <h1 style="width: 100%">О магазине</h1>
       <p>Этот проект является Курсовой работой студента СТМИиТ. Все что есть на сайте является демонстрацией знаний. Сайт не имеет торговых соглашений и связи с нологовой, так что сайт имеет только демонстративный характер.</p>
    </div>
</div>
{% endblock %}